apiVersion: v2
name: wallet
description: Microservice that handles crud operations on wallet resources
type: application
version: 2.7.2
appVersion: 2.7.2
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
